#!/usr/bin/env bash
# tui_modules.sh - GENERATED by tools/gen_load_order.sh from the "# requires:" headers of lib/ - do not edit.
# Sources every module after the modules it requires. Regenerate after adding a module or changing a header.
# shellcheck source=colors.sh
source "${SCRIPT_DIR}/colors.sh"
# shellcheck source=state.sh
source "${SCRIPT_DIR}/state.sh"
# shellcheck source=state_api.sh
source "${SCRIPT_DIR}/state_api.sh"
# shellcheck source=terminal_controls.sh
source "${SCRIPT_DIR}/terminal_controls.sh"
# shellcheck source=markup/tui_addon.sh
source "${SCRIPT_DIR}/markup/tui_addon.sh"
# shellcheck source=tui_api.sh
source "${SCRIPT_DIR}/tui_api.sh"
# shellcheck source=render/tui_async.sh
source "${SCRIPT_DIR}/render/tui_async.sh"
# shellcheck source=render/tui_canvas.sh
source "${SCRIPT_DIR}/render/tui_canvas.sh"
# shellcheck source=layout/tui_collapse.sh
source "${SCRIPT_DIR}/layout/tui_collapse.sh"
# shellcheck source=markup/tui_compose.sh
source "${SCRIPT_DIR}/markup/tui_compose.sh"
# shellcheck source=tui_configuration.sh
source "${SCRIPT_DIR}/tui_configuration.sh"
# shellcheck source=perf.sh
source "${SCRIPT_DIR}/perf.sh"
# shellcheck source=chrome/tui_dialog.sh
source "${SCRIPT_DIR}/chrome/tui_dialog.sh"
# shellcheck source=render/tui_emit.sh
source "${SCRIPT_DIR}/render/tui_emit.sh"
# shellcheck source=state/tui_epoch.sh
source "${SCRIPT_DIR}/state/tui_epoch.sh"
# shellcheck source=exec/tui_exec.sh
source "${SCRIPT_DIR}/exec/tui_exec.sh"
# shellcheck source=markup/tui_factory.sh
source "${SCRIPT_DIR}/markup/tui_factory.sh"
# shellcheck source=input/tui_focus.sh
source "${SCRIPT_DIR}/input/tui_focus.sh"
# shellcheck source=chrome/tui_footer.sh
source "${SCRIPT_DIR}/chrome/tui_footer.sh"
# shellcheck source=layout/tui_frame.sh
source "${SCRIPT_DIR}/layout/tui_frame.sh"
# shellcheck source=input/tui_hit.sh
source "${SCRIPT_DIR}/input/tui_hit.sh"
# shellcheck source=tui_home.sh
source "${SCRIPT_DIR}/tui_home.sh"
# shellcheck source=config/tui_config.sh
source "${SCRIPT_DIR}/config/tui_config.sh"
# shellcheck source=input/tui_input.sh
source "${SCRIPT_DIR}/input/tui_input.sh"
# shellcheck source=apps/tui_install.sh
source "${SCRIPT_DIR}/apps/tui_install.sh"
# shellcheck source=tui_job.sh
source "${SCRIPT_DIR}/tui_job.sh"
# shellcheck source=layout/tui_layout.sh
source "${SCRIPT_DIR}/layout/tui_layout.sh"
# shellcheck source=core/tui_loop.sh
source "${SCRIPT_DIR}/core/tui_loop.sh"
# shellcheck source=markup/tui_markup.sh
source "${SCRIPT_DIR}/markup/tui_markup.sh"
# shellcheck source=chrome/tui_modal.sh
source "${SCRIPT_DIR}/chrome/tui_modal.sh"
# shellcheck source=input/tui_mouse.sh
source "${SCRIPT_DIR}/input/tui_mouse.sh"
# shellcheck source=markup/tui_node.sh
source "${SCRIPT_DIR}/markup/tui_node.sh"
# shellcheck source=markup/tui_ops.sh
source "${SCRIPT_DIR}/markup/tui_ops.sh"
# shellcheck source=plugin/tui_own.sh
source "${SCRIPT_DIR}/plugin/tui_own.sh"
# shellcheck source=chrome/tui_cmd.sh
source "${SCRIPT_DIR}/chrome/tui_cmd.sh"
# shellcheck source=render/tui_paint.sh
source "${SCRIPT_DIR}/render/tui_paint.sh"
# shellcheck source=markup/tui_parse.sh
source "${SCRIPT_DIR}/markup/tui_parse.sh"
# shellcheck source=plugin/tui_plugin.sh
source "${SCRIPT_DIR}/plugin/tui_plugin.sh"
# shellcheck source=markup/tui_refresh.sh
source "${SCRIPT_DIR}/markup/tui_refresh.sh"
# shellcheck source=tui_registry.sh
source "${SCRIPT_DIR}/tui_registry.sh"
# shellcheck source=markup/tui_build.sh
source "${SCRIPT_DIR}/markup/tui_build.sh"
# shellcheck source=chrome/tui_layer.sh
source "${SCRIPT_DIR}/chrome/tui_layer.sh"
# shellcheck source=layout/tui_resize.sh
source "${SCRIPT_DIR}/layout/tui_resize.sh"
# shellcheck source=render/tui_rowcache.sh
source "${SCRIPT_DIR}/render/tui_rowcache.sh"
# shellcheck source=layout/tui_scroll.sh
source "${SCRIPT_DIR}/layout/tui_scroll.sh"
# shellcheck source=markup/tui_shell.sh
source "${SCRIPT_DIR}/markup/tui_shell.sh"
# shellcheck source=state/tui_store.sh
source "${SCRIPT_DIR}/state/tui_store.sh"
# shellcheck source=style/tui_style.sh
source "${SCRIPT_DIR}/style/tui_style.sh"
# shellcheck source=markup/tui_cache.sh
source "${SCRIPT_DIR}/markup/tui_cache.sh"
# shellcheck source=apps/tui_sync.sh
source "${SCRIPT_DIR}/apps/tui_sync.sh"
# shellcheck source=widgets/tui_text.sh
source "${SCRIPT_DIR}/widgets/tui_text.sh"
# shellcheck source=apps/tui_update.sh
source "${SCRIPT_DIR}/apps/tui_update.sh"
# shellcheck source=markup/tui_validate.sh
source "${SCRIPT_DIR}/markup/tui_validate.sh"
# shellcheck source=widgets/tui_widget_contract.sh
source "${SCRIPT_DIR}/widgets/tui_widget_contract.sh"
# shellcheck source=widgets/tui_widgets.sh
source "${SCRIPT_DIR}/widgets/tui_widgets.sh"
