#!/usr/bin/env bash
# cmd/build.sh - `dabt build`, plus the pieces `dabt pkg notes` shares with it (prepare: collect + metadata + changelog).

declare -g _WORK="" _EPOCH="" _BI_TYPE="" _BI_SRC="" _BI_TGT="" _BI_REC=0
declare -ga _BI_INC=()

_dapk.cmd.epoch() {
	local ct
	if [[ "${SOURCE_DATE_EPOCH:-}" =~ ^[0-9]+$ ]]; then
		_EPOCH="$SOURCE_DATE_EPOCH"
	elif ct="$(git -C "$1" log -1 --format=%ct 2>/dev/null)" && [[ "$ct" =~ ^[0-9]+$ ]]; then
		_EPOCH="$ct"
	else printf -v _EPOCH '%(%s)T' -1; fi
}

_dapk.cmd.flush_inc() {
	[[ -n "$_BI_TYPE" ]] || return 0
	[[ -n "$_BI_SRC" && -n "$_BI_TGT" ]] || {
		_dapk.cmd.usage "-f/-d needs both -s SOURCE and -t TARGET"
		return 2
	}
	_BI_INC+=("$_BI_TYPE|$_BI_SRC|$_BI_TGT|$_BI_REC")
	_BI_TYPE="" _BI_SRC="" _BI_TGT="" _BI_REC=0
}

# STAGE : make STAGE/.dabt.metadata agree with this build (version, name); generate one when the project has none
_dapk.cmd.metadata() {
	local f="$1/.dabt.metadata" line v name="${DAPK_CFG[name]}" ver="$DAPK_VERSION" tmp="$1/.dabt.metadata.tmp" sv=0 sn=0 mn
	if [[ -f "$f" ]]; then
		while IFS= read -r line || [[ -n "$line" ]]; do
			if [[ "$line" =~ ^([[:space:]]*name[[:space:]]*=[[:space:]]*)(.*)$ ]]; then
				v="${BASH_REMATCH[2]}"
				v="${v%"${v##*[![:space:]]}"}"
				[[ "$v" == "$name" ]] || dapk.ui.warn ".dabt.metadata name '$v' differs from the package name '$name': the package uses '$name'"
				line="${BASH_REMATCH[1]}$name"
				sn=1
			elif [[ "$line" =~ ^([[:space:]]*version[[:space:]]*=[[:space:]]*).* ]]; then
				line="${BASH_REMATCH[1]}$ver"
				sv=1
			fi
			printf '%s\n' "$line"
		done <"$f" >"$tmp"
		((sn)) || printf 'name        = %s\n' "$name" >>"$tmp"
		((sv)) || printf 'version     = %s\n' "$ver" >>"$tmp"
		mv -f "$tmp" "$f"
	else
		{
			printf '# generated by dabt build\nname        = %s\nversion     = %s\nentry       = %s\n' "$name" "$ver" "${DAPK_CFG[entry]:-}"
			[[ -n "${DAPK_CFG[title]:-}" ]] && printf 'title       = %s\n' "${DAPK_CFG[title]}"
			[[ -n "${DAPK_CFG[description]:-}" ]] && printf 'description = %s\n' "${DAPK_CFG[description]}"
			[[ -n "${DAPK_CFG[author]:-}" ]] && printf 'author      = %s\n' "${DAPK_CFG[author]}"
			mn="${DAPK_CFG[requires_dabt]:-}"
			[[ "$mn" =~ ^\>=[[:space:]]*([0-9][0-9.]*)$ ]] && printf 'min_dabt    = %s\n' "${BASH_REMATCH[1]}"
		} >"$f"
	fi
	chmod 644 "$f"
}

# STAGE : collect the files into STAGE (which must not exist)
_dapk.cmd.stage_files() {
	local stage="$1" entry="${DAPK_CFG[entry]:-}"
	dapk.collect.run "$stage" || {
		dapk.ui.err "$DAPK_COLLECT_ERROR"
		return 1
	}
	dapk.ui.ok "$DAPK_COLLECT_COUNT files"
	[[ -n "$entry" ]] || {
		dapk.ui.err "no entry script: set entry in dabt.pkg (or .dabt.metadata)"
		return 1
	}
	[[ -f "$stage/$entry" ]] || {
		dapk.ui.err "entry '$entry' is not part of the package"
		return 1
	}
}

# ROOT STAGE : .dabt.metadata, the changelog rewrite and NEWS inside STAGE. Needs DAPK_CFG, the version and _EPOCH.
_dapk.cmd.stage_meta() {
	local root="$1" stage="$2" cl rel date
	TZ=UTC printf -v date '%(%Y-%m-%d)T' "$_EPOCH"
	_dapk.cmd.metadata "$stage"
	dapk.ui.ok ".dabt.metadata: ${DAPK_CFG[name]} $DAPK_VERSION"
	rel="${DAPK_CFG[changelog]:-}"
	DAPK_NOTES_CHANGELOG=""
	if [[ -n "$rel" ]]; then
		cl="$root/$rel"
		if [[ ! -r "$cl" ]]; then
			dapk.ui.err "changelog '$rel' not found"
			return 1
		fi
		local label="$DAPK_VERSION"
		[[ "$DAPK_VERSION" == *-* ]] && label="$DAPK_FULL"
		[[ "$rel" == */* ]] && mkdir -p "$stage/${rel%/*}"
		if dapk.changelog.rewrite "$cl" "$stage/$rel" "$label" "$date"; then
			dapk.ui.ok "changelog: Unreleased -> [$label] - $date"
		else
			cp -- "$cl" "$stage/$rel"
			dapk.ui.warn "$rel has no '## [Unreleased]' section: nothing to close for $label"
		fi
		dapk.changelog.news "$stage/$rel" "$label" >"$stage/NEWS"
		local n
		n="$(wc -l <"$stage/NEWS")"
		dapk.ui.ok "News: ${n//[[:space:]]/} bullet(s)"
		chmod 644 "$stage/NEWS" "$stage/$rel"
		DAPK_NOTES_CHANGELOG="$stage/$rel" DAPK_NOTES_VERSION="$label"
	else dapk.ui.warn "no changelog configured: no News for this package"; fi
	return 0
}

_dapk.cmd.prepare() { _dapk.cmd.stage_files "$2" && _dapk.cmd.stage_meta "$1" "$2"; }

# fills DAPK_NOTES from the current build state; needs DAPK_MANIFEST_ENTRIES (from a scan) for the checksums
_dapk.cmd.notes_vars() {
	local root="$1" e t h s m p tag="$DAPK_TAG" repo cs="" news="" v x
	DAPK_NOTES=([name]="${DAPK_CFG[name]}" [version]="$DAPK_VERSION" [build]="$DAPK_BUILD" [date]="" [commit]="$(git -C "$root" rev-parse --short HEAD 2>/dev/null)")
	TZ=UTC printf -v x '%(%Y-%m-%d)T' "$_EPOCH"
	DAPK_NOTES[date]="$x"
	for e in "${DAPK_MANIFEST_ENTRIES[@]}"; do
		read -r t h s m p <<<"$e"
		cs+="$h  $p"$'\n'
	done
	DAPK_NOTES[checksums]="${cs%$'\n'}"
	if [[ -n "$DAPK_NOTES_CHANGELOG" ]]; then
		while IFS=$'\t' read -r v x; do [[ "$v" == "$DAPK_NOTES_VERSION" && -n "$x" ]] && news+="- $x"$'\n'; done < <(dapk.changelog.news "$DAPK_NOTES_CHANGELOG" "$DAPK_NOTES_VERSION")
	fi
	DAPK_NOTES[news]="${news%$'\n'}"
	repo="$(dapk.notes.repo_slug "$root")"
	DAPK_NOTES[compare_url]="$(dapk.notes.compare_url "$repo" "$tag" "$root")"
	# release-note images: the block-font headers live in the DABT repo (override with release_header_base); the version header and the logo
	# are files of the app's own repo, referenced at the release tag so they exist exactly when the release does
	local title="${DAPK_CFG[release_title]:-${DAPK_CFG[title]:-${DAPK_CFG[name]}}}" raw="" f
	[[ -n "$repo" ]] && raw="https://raw.githubusercontent.com/$repo/$tag"
	DAPK_NOTES[title]="$title"
	DAPK_NOTES[header_base]="${DAPK_CFG[release_header_base]:-https://raw.githubusercontent.com/DinosaursAreCute/DinosAmazingBashTui/main/assets/headers}"
	[[ -n "$DAPK_NOTES_CHANGELOG" ]] && DAPK_NOTES[summary]="$(dapk.changelog.intro "$DAPK_NOTES_CHANGELOG" "$DAPK_NOTES_VERSION")"
	DAPK_NOTES[logo]=""
	f="${DAPK_CFG[release_logo]:-}"
	[[ -n "$raw" && -n "$f" && -f "$root/$f" ]] && DAPK_NOTES[logo]="$raw/$f"
	f="$(dapk.header.version_file "$DAPK_VERSION")"
	if [[ -n "$raw" && -f "$root/$f" ]]; then
		DAPK_NOTES[heading]="<h1><img src=\"$raw/$f\" alt=\"$title $DAPK_VERSION\" height=\"50\"></h1>"
	else DAPK_NOTES[heading]="# $title $DAPK_VERSION"; fi
}

_dapk.cmd.tpl_path() {
	local t="${DAPK_CFG[release_template]}"
	[[ "$t" == /* ]] && printf '%s' "$t" || printf '%s/%s' "$DAPK_ROOT" "$t"
}

_dapk.cmd.build_run() {
	local root="$1" outdir="$2" suffix="$3" plan="$4" nosign="$5" key="$6" autosign="$7" stage pkg root_name fp="" repo built commit x i
	dapk.ui.steps "$( ((plan)) && echo 2 || echo 7)"

	dapk.ui.step "Configuration"
	dapk.config.load "$root" || {
		dapk.ui.err "$DAPK_CONFIG_ERROR"
		return 1
	}
	for x in "${DAPK_CONFIG_UNKNOWN[@]}"; do dapk.ui.warn "dabt.pkg: unknown key '$x' (ignored)"; done
	dapk.version.resolve "$root" "$suffix" "${DAPK_CFG[build_offset]:-0}" || {
		dapk.ui.err "$DAPK_VERSION_ERROR"
		return 1
	}
	for ((i = 0; i < ${#_BI_INC[@]}; i++)); do
		IFS='|' read -r t s g r <<<"${_BI_INC[i]}"
		dapk.config.add_include "$t" "$s" "$g" "$r"
	done
	_dapk.cmd.epoch "$root"
	dapk.ui.kv name "${DAPK_CFG[name]}"
	dapk.ui.kv version "$DAPK_FULL  ($DAPK_VERSION_SOURCE)"
	dapk.ui.kv build "$DAPK_BUILD  ($DAPK_BUILD_SOURCE)"
	[[ -n "$DAPK_BUILD_NOTE" ]] && dapk.ui.warn "$DAPK_BUILD_NOTE"
	[[ -n "${DAPK_CFG[entry]:-}" ]] && dapk.ui.kv entry "${DAPK_CFG[entry]}"
	if ((! nosign && ! plan)); then
		dapk.sign.resolve_key "$key" "${DAPK_CFG[sign_key]:-}" "$autosign" || {
			dapk.ui.err "$DAPK_SIGN_ERROR"
			return 1
		}
		fp="$(dapk.sign.fingerprint "$DAPK_SIGN_KEYFILE")"
		[[ -n "$fp" ]] || {
			dapk.ui.err "cannot read the signing key $DAPK_SIGN_KEYFILE"
			return 1
		}
		dapk.ui.kv signer "$fp"
		[[ "$DAPK_SIGN_KEYFILE" == "$(dapk.sign.default_key)" ]] && dapk.ui.kv key "$DAPK_SIGN_KEYFILE"
	elif ((nosign)); then dapk.ui.warn "building without a signature (--no-sign): the package cannot be installed without --allow-unsigned"; fi

	dapk.ui.step "Collecting files"
	_WORK="$(mktemp -d "${TMPDIR:-/tmp}/dapk_build.XXXXXX")" || return 1
	root_name="${DAPK_CFG[name]}-$DAPK_FULL"
	stage="$_WORK/$root_name"
	if ((plan)); then
		DAPK_COLLECT_DRY=1
		dapk.collect.run "$stage" || {
			dapk.ui.err "$DAPK_COLLECT_ERROR"
			return 1
		}
		dapk.ui.step "Plan"
		printf '%s\n' "${DAPK_COLLECT_PLAN[@]}"
		dapk.ui.ok "$DAPK_COLLECT_COUNT files, nothing written"
		return 0
	fi
	_dapk.cmd.stage_files "$stage" || return 1

	dapk.ui.step "Changelog and metadata"
	_dapk.cmd.stage_meta "$root" "$stage" || return 1

	dapk.ui.step "Manifest"
	DAPK_MANIFEST_PROGRESS=1 dapk.manifest.scan "$stage" || {
		dapk.ui.err "$DAPK_MANIFEST_ERROR"
		return 1
	}
	TZ=UTC printf -v built '%(%Y-%m-%dT%H:%M:%SZ)T' "$_EPOCH"
	commit="$(git -C "$root" rev-parse --short HEAD 2>/dev/null)"
	repo="$(dapk.notes.repo_slug "$root")"
	_DM_HDR=()
	dapk.manifest.header_set name "${DAPK_CFG[name]}"
	dapk.manifest.header_set version "$DAPK_VERSION"
	dapk.manifest.header_set build "$DAPK_BUILD"
	[[ -n "$commit" ]] && dapk.manifest.header_set commit "$commit"
	dapk.manifest.header_set built "$built"
	dapk.manifest.header_set entry "${DAPK_CFG[entry]}"
	[[ -n "${DAPK_CFG[requires_dabt]:-}" ]] && dapk.manifest.header_set requires_dabt "${DAPK_CFG[requires_dabt]}"
	x="${DAPK_CFG[homepage]:-}"
	[[ -z "$x" && -n "$repo" ]] && x="https://github.com/$repo"
	[[ -n "$x" ]] && dapk.manifest.header_set homepage "$x"
	[[ -n "$repo" ]] && dapk.manifest.header_set news_url "https://github.com/$repo/releases/latest/download/${DAPK_CFG[name]}-news.txt"
	[[ -n "$fp" ]] && dapk.manifest.header_set signer "$fp"
	dapk.deps.load_config
	dapk.deps.header
	dapk.manifest.write "$stage/MANIFEST" || {
		dapk.ui.err "cannot write MANIFEST"
		return 1
	}
	dapk.ui.ok "MANIFEST: ${#DAPK_MANIFEST_ENTRIES[@]} top-level entries$( ((DAPK_DEPS_N)) && echo ", $DAPK_DEPS_N dependenc$( ((DAPK_DEPS_N == 1)) && echo y || echo ies)")"

	dapk.ui.step "Signing"
	if ((nosign)); then
		dapk.ui.info "skipped (--no-sign)"
	else dapk.ui.run "Signing MANIFEST" dapk.sign.sign "$stage/MANIFEST" "$DAPK_SIGN_KEYFILE" || {
		dapk.ui.err "$DAPK_SIGN_ERROR"
		return 1
	}; fi
	dapk.sign.cleanup

	dapk.ui.step "Packing"
	mkdir -p "$outdir" || return 1
	pkg="$outdir/$root_name.$DABT_PKG_EXT"
	dapk.pack.create "$_WORK" "$root_name" "$pkg" "$_EPOCH" || {
		dapk.ui.err "$DAPK_PACK_ERROR"
		return 1
	}
	x="$(dapk.manifest.sha256 "$pkg")"
	printf '%s  %s\n' "$x" "${pkg##*/}" >"$pkg.sha256"
	[[ -f "$stage/NEWS" ]] && cp -- "$stage/NEWS" "$outdir/${DAPK_CFG[name]}-news.txt"
	dapk.ui.ok "${pkg##*/}  ($(wc -c <"$pkg" | tr -d ' ') bytes)"
	dapk.ui.kv sha256 "$x"

	dapk.ui.step "Release notes"
	_dapk.cmd.notes_vars "$root"
	if dapk.notes.render "$(_dapk.cmd.tpl_path)" "$outdir/RELEASE_NOTES.md"; then
		dapk.ui.ok "RELEASE_NOTES.md"
	else
		dapk.ui.err "$DAPK_NOTES_ERROR"
		return 1
	fi
	printf '%s\n' "$pkg"
	return 0
}

dapk.cmd.build() {
	local dir="." suffix="" plan=0 nosign=0 key="" outdir="" rc root autosign=0
	_BI_INC=()
	_BI_TYPE="" _BI_SRC="" _BI_TGT="" _BI_REC=0
	while (($#)); do
		if _dapk.cmd.ui "$1" "${2:-}"; then
			shift "$_UI_SHIFT"
			continue
		fi
		case "$1" in
			--suffix)
				[[ -n "${2:-}" ]] || {
					_dapk.cmd.usage "--suffix needs a value"
					return 2
				}
				suffix="$2"
				shift 2
				;;
			--out)
				outdir="$2"
				shift 2
				;;
			--key)
				key="$2"
				shift 2
				;;
			--no-sign)
				nosign=1
				shift
				;;
			--auto-sign)
				autosign=1
				shift
				;;
			--plan)
				plan=1
				shift
				;;
			--allow-external)
				DAPK_COLLECT_ALLOW_EXTERNAL=1
				shift
				;;
			-f | --file)
				_dapk.cmd.flush_inc || return 2
				_BI_TYPE=file
				shift
				;;
			-d | --directory)
				_dapk.cmd.flush_inc || return 2
				_BI_TYPE=directory
				shift
				;;
			-s | --source)
				[[ -n "$_BI_TYPE" ]] || {
					_dapk.cmd.usage "-s needs a preceding -f or -d"
					return 2
				}
				_BI_SRC="${2:-}"
				shift 2
				;;
			-t | --target)
				[[ -n "$_BI_TYPE" ]] || {
					_dapk.cmd.usage "-t needs a preceding -f or -d"
					return 2
				}
				_BI_TGT="${2:-}"
				shift 2
				;;
			-r | --recursive)
				[[ "$_BI_TYPE" == directory ]] || {
					_dapk.cmd.usage "-r applies to -d entries"
					return 2
				}
				_BI_REC=1
				shift
				;;
			-h | --help)
				_dapk.cmd.help
				return 0
				;;
			-*)
				_dapk.cmd.usage "build: unknown option $1"
				return 2
				;;
			*)
				dir="$1"
				shift
				;;
		esac
	done
	_dapk.cmd.flush_inc || return 2
	root="$(cd -P "$dir" 2>/dev/null && pwd -P)" || {
		_dapk.cmd.usage "build: '$dir' is not a folder"
		return 2
	}
	[[ -n "$outdir" ]] || outdir="$root/dist"
	if ((! plan)) && [[ -z "$DAPK_UI_LOG_FILE" ]]; then mkdir -p "$outdir" && DAPK_UI_LOG_FILE="$outdir/build.log"; fi
	dapk.ui.init
	((DAPK_UI_QUIET)) || printf '%sD.A.B.T%s build  %s%s%s\n' "$BLUE" "$R" "$D" "$(<"$TUI_ROOT/VERSION")" "$R" >&2
	trap 'rm -rf "$_WORK"; dapk.sign.cleanup; dapk.ui.cleanup' EXIT
	_dapk.cmd.build_run "$root" "$outdir" "$suffix" "$plan" "$nosign" "$key" "$autosign"
	rc=$?
	[[ -n "$_WORK" ]] && rm -rf "$_WORK"
	_WORK=""
	trap - EXIT
	_dapk.cmd.finish "$rc"
}
