#!/usr/bin/env bash
# gen_load_order.sh - writes lib/tui_modules.sh, the list tui.sh sources, by sorting the lib/ modules on their headers.
#
#   tools/gen_load_order.sh            (re)generate lib/tui_modules.sh
#   tools/gen_load_order.sh --check    exit 1 when lib/tui_modules.sh is stale (a header changed, a module was added)
#   tools/gen_load_order.sh --order [SEED]   print the load order only; SEED shuffles the tie-break, which finds modules
#                                      that depend on another without saying so (any valid order must still work)
#
# A module is a lib/*.sh or lib/*/*.sh file with a "# requires:" line in its leading comment block. The value lists the
# modules (file names without .sh) whose functions or variables it uses WHILE IT IS SOURCED - top-level calls and
# top-level reads. Calls made later, from inside functions, do not belong there. Ties sort by name.
# A cycle or an unknown module name stops with the offending names.
set -uo pipefail
shopt -s nullglob # a lib/ without subdirectories must not leave the literal pattern in the loop
cd "$(dirname "$0")/.." || exit 1
LIB=${LIB:-lib} # tests point it at a fixture directory

mode=generate seed=""
case "${1:-}" in
	--check) mode=check ;;
	--order) mode=order seed="${2:-}" ;;
	"") ;;
	*)
		echo "usage: gen_load_order.sh [--check | --order [SEED]]" >&2
		exit 2
		;;
esac

declare -A path req indeg
names=()
for f in "$LIB"/*.sh "$LIB"/*/*.sh; do
	line=$(awk '!/^#/ {exit} /^# requires:/ {sub(/^# requires:[ \t]*/, ""); print "R " $0; found = 1; exit} END {if (!found) print "-"}' "$f")
	[[ $line == "-" ]] && continue
	name=${f##*/}
	name=${name%.sh}
	if [[ -n ${path[$name]:-} ]]; then
		echo "gen_load_order: module name '$name' is used by ${path[$name]} and $f" >&2
		exit 1
	fi
	path[$name]=${f#"$LIB"/}
	req[$name]=${line#R }
	names+=("$name")
done

for name in "${names[@]}"; do
	indeg[$name]=0
	for dep in ${req[$name]}; do
		if [[ -z ${path[$dep]:-} ]]; then
			echo "gen_load_order: $name requires '$dep', which is not a module (no such file or no '# requires:' header)" >&2
			exit 1
		fi
		indeg[$name]=$((indeg[$name] + 1))
	done
done

# Kahn: repeatedly load the modules whose requirements are all loaded
order=()
declare -A done_
remaining=${#names[@]}
while ((remaining > 0)); do
	ready=()
	for name in "${names[@]}"; do
		[[ -n ${done_[$name]:-} ]] && continue
		ok=1
		for dep in ${req[$name]}; do [[ -z ${done_[$dep]:-} ]] && {
			ok=0
			break
		}; done
		((ok)) && ready+=("$name")
	done
	if ((${#ready[@]} == 0)); then
		stuck=()
		for name in "${names[@]}"; do [[ -z ${done_[$name]:-} ]] && stuck+=("$name (requires ${req[$name]})"); done
		printf 'gen_load_order: dependency cycle among:\n' >&2
		printf '  %s\n' "${stuck[@]}" >&2
		exit 1
	fi
	if [[ -n $seed ]]; then
		RANDOM=$((seed + remaining))
		pick=${ready[$((RANDOM % ${#ready[@]}))]}
	else
		pick=$(printf '%s\n' "${ready[@]}" | sort | head -n1)
	fi
	order+=("$pick")
	done_[$pick]=1
	((remaining--))
done

if [[ $mode == order ]]; then
	printf '%s\n' "${order[@]}"
	exit 0
fi

out=$(
	cat <<'HEADER'
#!/usr/bin/env bash
# tui_modules.sh - GENERATED by tools/gen_load_order.sh from the "# requires:" headers of lib/ - do not edit.
# Sources every module after the modules it requires. Regenerate after adding a module or changing a header.
HEADER
	for name in "${order[@]}"; do
		printf '# shellcheck source=%s\nsource "${SCRIPT_DIR}/%s"\n' "${path[$name]}" "${path[$name]}"
	done
)
if [[ $mode == check ]]; then
	if [[ "$out" == "$(cat "$LIB/tui_modules.sh" 2>/dev/null)" ]]; then exit 0; fi
	echo "gen_load_order: $LIB/tui_modules.sh is stale - run tools/gen_load_order.sh" >&2
	exit 1
fi
printf '%s\n' "$out" >"$LIB/tui_modules.sh"
printf 'gen_load_order: %d modules -> %s/tui_modules.sh\n' "${#order[@]}" "$LIB"
